// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNbykNx2bmREmd5JKyp9UtuKDOSdif68I',
    appId: '1:379945935699:web:a8b1e5230694e701e877a6',
    messagingSenderId: '379945935699',
    projectId: 'task-manager-bb',
    authDomain: 'task-manager-bb.firebaseapp.com',
    storageBucket: 'task-manager-bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ1OhXVmZ864Ars9611CxiCbssEcZMscY',
    appId: '1:379945935699:android:3d6300e931e74604e877a6',
    messagingSenderId: '379945935699',
    projectId: 'task-manager-bb',
    storageBucket: 'task-manager-bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-AJOEE7ppiwmlhfhGrc5ZeYSp6Cb9x5A',
    appId: '1:379945935699:ios:5798641093022d39e877a6',
    messagingSenderId: '379945935699',
    projectId: 'task-manager-bb',
    storageBucket: 'task-manager-bb.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-AJOEE7ppiwmlhfhGrc5ZeYSp6Cb9x5A',
    appId: '1:379945935699:ios:5798641093022d39e877a6',
    messagingSenderId: '379945935699',
    projectId: 'task-manager-bb',
    storageBucket: 'task-manager-bb.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNbykNx2bmREmd5JKyp9UtuKDOSdif68I',
    appId: '1:379945935699:web:57290fca0951d16de877a6',
    messagingSenderId: '379945935699',
    projectId: 'task-manager-bb',
    authDomain: 'task-manager-bb.firebaseapp.com',
    storageBucket: 'task-manager-bb.firebasestorage.app',
  );
}
