// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeKEjO2_aqPpXOOYlwEa327V9AgiFW6u4',
    appId: '1:388989731754:web:3bb3d5b33b0a73e16e61d3',
    messagingSenderId: '388989731754',
    projectId: 'ecommerce-app-bbi',
    authDomain: 'ecommerce-app-bbi.firebaseapp.com',
    storageBucket: 'ecommerce-app-bbi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7fAUoVdHpBr6oXKEdAKD5zmRdFgcTX2U',
    appId: '1:388989731754:android:b73c26164b84226f6e61d3',
    messagingSenderId: '388989731754',
    projectId: 'ecommerce-app-bbi',
    storageBucket: 'ecommerce-app-bbi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyBKVxSWbSWbA5ludPi46ZUO-rS-wdTAA',
    appId: '1:388989731754:ios:f40108f3d08693196e61d3',
    messagingSenderId: '388989731754',
    projectId: 'ecommerce-app-bbi',
    storageBucket: 'ecommerce-app-bbi.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyBKVxSWbSWbA5ludPi46ZUO-rS-wdTAA',
    appId: '1:388989731754:ios:f40108f3d08693196e61d3',
    messagingSenderId: '388989731754',
    projectId: 'ecommerce-app-bbi',
    storageBucket: 'ecommerce-app-bbi.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeKEjO2_aqPpXOOYlwEa327V9AgiFW6u4',
    appId: '1:388989731754:web:fe8edb4eafcb0e5e6e61d3',
    messagingSenderId: '388989731754',
    projectId: 'ecommerce-app-bbi',
    authDomain: 'ecommerce-app-bbi.firebaseapp.com',
    storageBucket: 'ecommerce-app-bbi.firebasestorage.app',
  );
}
